AllCops:
  Exclude:
    - "bin/**/*"
    - "lib/templates/**/*"
    - "db/schema.rb"

Rails:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: "double_quotes"

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: "rails"

